---
direction: Horizontal
parts:
  - direction: Vertical
    split_size:
      Fixed: 1
    run:
      plugin: tab-bar
  - direction: Vertical
  - direction: Vertical
    split_size:
      Fixed: 2
    run:
      plugin: status-bar
