[package]
name = "zellij-client"
version = "0.42.0"
authors = ["Kunal Mohan <kunalmohan99@gmail.com>"]
edition = "2021"
description = "The client-side library for Zellij"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = { version = "0.7.11", features = ['os-ext'] }
serde = { version = "1.0", features = ["derive"] }
url = { version = "2.2.2", features = ["serde"] }
serde_yaml = "0.8"
serde_json = "1.0"
zellij-utils = { path = "../zellij-utils/", version = "0.42.0" }
log = "0.4.17"
# TODO: consider moving these to zellij-utils
tokio = { version = "1.38.1", features = ["full"], optional = true }
tokio-tungstenite = { version = "0.23.1", optional = true }
futures = { version = "0.3.30", optional = true }
axum = { version = "0.8.1", features = ["ws"], optional = true }
tower = { version = "0.5.2", optional = true }

[dev-dependencies]
insta = "1.6.0"

[features]
unstable = []
web_server_capability = [
    "dep:tokio",
    "dep:tokio-tungstenite",
    "dep:futures",
    "dep:axum",
    "dep:tower",
]
